### ISSUE TITLE
All gem versions show as released on September 22 2012

### ISSUE THREAD

**Issue by elifoster** [kylewlacy/timerizer#5]
Because of [this line](https://github.com/kylewlacy/timerizer/blob/master/timerizer.gemspec#L6) and it not getting updated when a new gem version is released, [every single version](https://rubygems.org/gems/timerizer/versions) except 0.0.1 appear as released on Sept 22 2012.

The gem cli will actually set the date for you if it's not specified, so you don't really need that line.

**Comment by kylewlacy** [comment]
Okay, just fixed the gemspec, thanks for the bug report! I decided to publish a new version which has the date metadata set properly, as well as the MIT license (which I mentioned under #4 and which I reached out to @cesarfigueroa about through another channel, so that covers all the contributors to the project so far)
